### PR TITLE
Add LOGOUT_LINK capability

### PR DESCRIPTION
**Pull request by IshentRas**
Add the capability of defining the Logout link (https://github.com/openshift/origin-server/pull/5779)

### CODE REVIEW

**Comment by Miciah** [comment]
Please [test]!

**Comment by Miciah** [comment]
Odd—openshift-bot has commented on other PRs in this repository, but is not responding to me for whatever reason.  Anyway, the PR looks good.  Thanks!

**Comment by sdodson** [comment]
[test] ?

**Comment by Miciah** [comment]
[test] worked on 312 but not here.  Maybe that functionality has been disabled.

**Pull request merged**
